### ISSUE TITLE
[TASK] Futures: Pausing / price divergence circuit breaker

### ISSUE THREAD

**Issue by zyzek** [Synthetixio/issues#141]
- [x] Determine whether futures markets need to be pausable from SystemStatus
- [x] Ensure futures markets are properly responsive to the other system status statuses (e.g. SystemInactive)
- [x] Allow the contract to pause if the last price received was clearly incorrect
- [x] Decide what the deviation threshold should be
- [x] Do not allow positions to be opened or closed while paused, but allow existing orders to be cancelled.
- [x] Ensure this is consistent with existing synth pause functionality (share what can be shared)
- [x] Do not charge funding etc. during the price freeze.
- [x] Determine unfreezing process
- [x] Tests

Relevant SIPs:

https://sips.synthetix.io/sips/sip-55
https://sips.synthetix.io/sips/sip-65
https://sips.synthetix.io/sips/sip-78
https://sips.synthetix.io/sips/sip-139

Most of the relevant code is in `Exchanger.sol`, from recollection.

**Comment by artdgn** [comment]
### https://github.com/Synthetixio/synthetix/pull/1530 should take care of:
- Determine whether futures markets need to be pausable from SystemStatus  :heavy_check_mark: 
- Ensure futures markets are properly responsive to the other system status statuses (e.g. SystemInactive)  :heavy_check_mark: 
- Do not allow positions to be opened or closed while paused, but allow existing orders to be cancelled. :question: :heavy_check_mark: 
> Not sure what "allow existing orders to be cancelled" refers to. It seems that `modifyPosition` completes in same transaction.
- Do not charge funding etc. during the price freeze. :heavy_check_mark: 
- Determine unfreezing process: **through the existing mechanism ** :heavy_check_mark: 

### Remaining:
 - Decide what the deviation threshold should be: will start with the previous values in `Exchanger` :heavy_check_mark: 
 - Ensure this is consistent with existing synth pause functionality (share what can be shared) :hourglass: 
 
### Rough plan:
The plan is to share the functionality of saving and checking `lastExchangeRate` between `Exchanger` and `FuturesMarket` through `ExchangeRates`.

**Comment by artdgn** [comment]
https://github.com/Synthetixio/synthetix/pull/1540 Is about having the circuit breaker mutable functionality (triggering last-rate update) accessible from `FuturesMarket` by refactoring the circuit breaker into a separate from `Exchanger` contract.

**Comment by artdgn** [comment]
https://github.com/Synthetixio/synthetix/pull/1547 is about merging develop into `futures-implementation` in order to reduce divergence and make CI green again. 
So the order of PRs to merge is now:
1. https://github.com/Synthetixio/synthetix/pull/1547 - merge develop
2. https://github.com/Synthetixio/synthetix/pull/1530 - listen to system status
3. https://github.com/Synthetixio/synthetix/pull/1540 - refactor circuit breaker
4. https://github.com/Synthetixio/synthetix/pull/1567 - add usage of circuit breaker from futures
