### ISSUE TITLE
[TASK]: Double check the interest rate on the loans as a side effect of futures

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#170]
### Summary

We need to double check if the interest rates on the loans are still valid once futures (short-long skew)

**Comment by zyzek** [comment]
It looks like futures and the multicollateral system will have to communicate. In particular, futures markets will need to inject their skew information into `CollateralManager.getShortRate`, and each futures market may have to read the skew information from the multicollateral system. We will need to work out this stuff in more detail, but the status quo is that the short interest rates will not reflect the skew induced by futures markets, which they probably need to respect. It's a more interesting question whether futures markets will need to understand the skew induced by the synth and multicollateral systems, or whether it is sufficient to allow the skew to be corrected on futures markets by themselves and let arbitrage sort the rest out.

For now, I'm going to park this ticket, it will need to be revisited when @barrasso has concluded the L2 shorts work, and then the integration work can commence without interfering with his progress.
