### ISSUE TITLE
Fix debt pool stat in staking dapp

### ISSUE THREAD

**Issue by kelonye** [Synthetixio/issues#203]
| correct ✅ |  wrong ❌ |
|---|---|
| <img width="538" alt="Screenshot 2021-06-17 at 19 36 05" src="https://user-images.githubusercontent.com/60554509/122438361-4e95ef80-cfa3-11eb-92f4-53febb5a79e5.png"> | <img width="323" alt="Screenshot 2021-06-17 at 19 36 09" src="https://user-images.githubusercontent.com/60554509/122438335-46d64b00-cfa3-11eb-8977-1102525ec29b.png"> |

## QA Tasks
- PR https://github.com/Synthetixio/staking/pull/577
- Visit https://staking-git-fix-debt-chart-synthetixio.vercel.app/debt
- Ensure the -ve sETH skew is properly computed.
- Ensure it's red in color with a warning tooltip.

**Comment by gberg1** [comment]
https://gist.github.com/justinjmoses/8e5046125384fbcdcf8b3c042f3e177a

**Comment by gberg1** [comment]
To calculate the % of the total debt pool

Step 1: Get the net skew (see gist above)
Step 2: Determine the sUSD value of the skew for each synth (use BaseDebtCache.sol)
Step 3: Get the total supply of all debt in sUSD 
Step 4: Calculate %'s

**Comment by kelonye** [comment]
Hey @gberg1. Thoughts on this https://github.com/Synthetixio/stats/blob/master/sections/Synths/index.tsx#L169-L189
