### ISSUE TITLE
[TASK]: Collateral contracts refactoring

### ISSUE THREAD

**Issue by barrasso** [Synthetixio/issues#264]
### Summary

Need to refactor and reduce the size of the contracts related to shorting in order to deploy to L2.

**Contracts:**

- [x] (~0.26%) Use `manager` interface directly
- [x] (~0.67%) Remove `getReward` function from `CollateralShort`
- [x] (~1.81%) Decrease require string sizes
- [x] (~4.4%) Move setters to Settings contracts
- [x] (~4.5%) Move accrue interest to `manager`
- [x] (~5.93%) Move view functions to Util contract
- [x] (~15.00%) Move loan storage from external state pattern to internal mapping

**Tests:**

- [x] Update `getReward` tests from in `ShortingRewards.js`
- [x] Update tests due to removal of `CollateralState` loan storage
- [x] Update tests due to settings and manager refactor
- [x] Fix unit tests relying on `CollateralUtil`
- [x] Fix `repayWithCollateral` unit test case 
- [x] Add `CollateralUtil.js` unit tests
- [x] Update integration tests to discern between the legacy and new Collateral contracts

**Misc:**

  - [x] Update deploy scripts for L2
  - [x] Deploy `CollateralUtil` contract
  - [x] Add return variables to Collateral functions
  - [x] Add automatic closure of loans if repaid in full 
  - [x] Fix `SystemSettings` setter function param ordering
  - [x] Fix inconsistencies with underscores in internal functions
  - [x] Update and resolve comments in Collateral contracts
  - [x] Update `releases.json` to have an entry for these changes (SIP-135)

  
  **PRs:**
- https://github.com/Synthetixio/synthetix/pull/1448
- https://github.com/Synthetixio/synthetix/pull/1427

**Comment by barrasso** [comment]
Justification for removing `getRewards` from `CollateralShort.sol`:

Shorting rewards can be claimed directly on the reward contract instead of proxying through the shorts contract.

This removes extra function in CollateralShort to getRewards which reduces the deploy contract size for CollateralShort.

**Comment by jacko125** [comment]
@barrasso  Ensure that the new `Collateral.sol` is updated so that the `loan.interactionDelay` isn't updated on actions that don't change the `shorts position` such as 

- Adding Collateral
- Withdrawing Collateral

**Comment by barrasso** [comment]
For `ovm` deployment:

1) [ ] Make sure `interactionDelay` is set to `0`.

2) [x] Make sure `minCollateral` is set to `0`.

3) [x] Make sure `collapseFeeRate` is set to ~~15 bps~~ 0 by default.

4) [x] Ensure the `CollateralManager` has all Collateral contracts added. Only `CollateralShort` should be added to L2.

5) [x] Deploy shorting rewards process

6) [ ] Is it necessary to filter shortable synths using `getSynths`?

7) [x] Make sure to upgrade `sUNI` and `sAAVE`

**Comment by barrasso** [comment]
Add CollateralShort object to params. (Related to: setting `minCollateral`)
