### ISSUE TITLE
[TASK]: SIP-187 Fix Partial Updates on Debt Cache

### ISSUE THREAD

**Issue by liamzebedee** [Synthetixio/issues#346]
SIP - https://sips.synthetix.io/sips/sip-187/

Note: See https://etherscan.io/tx/0x3d8f1ccca113d41e06953bd96af9e2f722341aca7e33d7cc0a3fa65525c902b8

PR - https://github.com/Synthetixio/synthetix/pull/1551

 - [ ] Implementation
 - [ ] Audit
 - [ ] Release
 - [ ] Postmortem writeup

**Comment by andytcf** [comment]
Released in Kaus
