### ISSUE TITLE
[TASK] Futures: Time Weighted Funding Rate model

### ISSUE THREAD

**Issue by jacko125** [Synthetixio/issues#367]
## Summary

Analysis of different funding rate time weighted parameters to see if time weighting of 1 is good enough

- [ ] do we need the time weighted funding rate for Arbitrageurs ? (Darius)

**Comment by jacko125** [comment]
Follow up with Afif and Darius on where the analysis of the TWFR model is needed

**Comment by artdgn** [comment]
@jacko125 shouldn't this be closed for now given the previous sim results?

**Comment by cavalier-eth** [comment]
closed as dont think we will do this
