### ISSUE TITLE
[TASK]: SIP-165 Debt Shares Oracle

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#376]
### Summary
https://www.notion.so/SIP-165-Debt-Pool-Synthesis-a466247bc40d4dc9bccb89756128c80f

**Comment by dbeal-eth** [comment]
likely changes isolated into a branch, just needs a little more cleanup atm:

https://github.com/Synthetixio/synthetix/compare/sip-185-debt-shares...sip-165-oracles

**Comment by cavalier-eth** [comment]
likey going to audit this week
