### ISSUE TITLE
Jan updates for subgraphs

### ISSUE THREAD

**Issue by dbeal-eth** [Synthetixio/issues#404]
* [x] add aggregators for price feeds (ex. like dailySNXPrice except for every synth also, with more flexibility) https://github.com/Synthetixio/synthetix-subgraph/pull/160
* [ ] add support for better Fee Pool metrics (ex. fees collected, fees to be distributed, inflation, etc.)
* [x] any other bug fixes we have received since the last release

**Comment by noahlitvin** [comment]
Currently looking into the Loans entity (currently empty) and iterating on the DailyCandles entity to support additional timeframes.
