### ISSUE TITLE
Cleanup legacy contracts that are hindering the deployment process

### ISSUE THREAD

**Issue by barrasso** [Synthetixio/issues#424]
e.g.

- [ ] x
- [ ] SystemSettingsLib will not verify, but verify.js says it already is verified?
- [ ] Had to remove ProxyERC20 and ProxySynthetix from the list of contracts requiring ownership because it can’t accept a nomination twice.
- [ ] Mistakenly adds CollateralEth to the migrate contract. 
    - Note: Maybe this is because of the index.js parameter mismatch? (ie. it was initially deployed with ISSUE_FEE_RATE: w3utils.toWei('0.001') but then later set to 0)

**Comment by cavalier-eth** [comment]
done (mostly)
