### ISSUE TITLE
more futures markets and supporting work

### ISSUE THREAD

**Issue by artdgn** [Synthetixio/issues#446]
- [x] SIP https://sips.synthetix.io/sips/sip-217/ existing crypto synths + gold & silver + non-synth market (luna)
- [x] release to kovan
- [x] pausing automation

Mainnet caveats:
- [x] CL feeds being checked
- [x] commodities deployed paused until automation ready
- [x] kwenta fixes for first batch of issues
- [x] kwenta updates and another round of QA on kovan

**Comment by cavalier-eth** [comment]
- [x] @cavalier-eth map out synths/layers availability then figure out governance

**Comment by artdgn** [comment]
https://github.com/Synthetixio/synthetix/pull/1736

**Comment by cavalier-eth** [comment]
Ideally released to kovan today for testing. 

- [ ] Mainnet still needs pausing bot figured out

**Comment by 0xjocke** [comment]
Pausing bot meeting takeaways:
Needs to be done:
- Add support for optimism.  Providers/ gasPrice
- Add support for optimism-kovan. Providers/ gasPrice
- Pause futures (not only synths)
- Look into using chainlink price round in combination with API. 
- Look into adding new API, (currently only relying on 1forge)

Good to have
- Some tests
- Easy way to run locally

**Comment by cavalier-eth** [comment]
- [x] @cavalier-eth get confirmation from CL and Kaleb

**Comment by artdgn** [comment]
Also flagged as important:
- tenderly alerting on failed txs from the bot
- some alerting on markets not being paused when expected (e.g. 1 hour after expected pause). Can be done using a tenderly action (on schedule) that triggers a tenderly alert

**Comment by cavalier-eth** [comment]
- [ ] @cavalier-eth follow up with Kewnta

**Comment by artdgn** [comment]
Basic monitoring for suspensions can be built on dune. A dashboard can be built from results of queries like this one: https://dune.xyz/queries/597835

**Comment by 0xjocke** [comment]
Synth suspension dashboard started, currently only optimism. Waiting for mainnet contract to be indexed by Dune
https://dune.xyz/joeyb/Synth-closures

**Comment by artdgn** [comment]
Market closure & alerting done
