### ISSUE TITLE
per asset stale period

### ISSUE THREAD

**Issue by artdgn** [Synthetixio/issues#448]
Right now the rate stale period is one global setting but different feeds have different heartbeat timeouts. 

The setting needs to be updated to be per asset. Or at least be able to set per asset override for the global setting. This way everything will be 20 minutes, and some exceptions will have different settings.

Or CL will have a minimal heartbeat that's smaller.

**Comment by cavalier-eth** [comment]
requested from CL and we;ll follow up this week
