### ISSUE TITLE
[NEW SYNTH]: sCOIN Synth & sMSFT

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#49]
New Synth Listing Checklist:

- [ ] Lanch date established
- [x] Synth icon made 
- [ ] Relevant ecosystem members informed 
- [ ] Incentives established
- [ ] Announcement prepared
- [ ] Synthetix.exchange / Kwenta support
- [x] Graph support for price updates
- [x] Feeds running on CL + aggregator on mainnet
- [x] Market closures for NYSE and bot
- [ ] Aftermarket trading pool (Balancer pool) 
- [ ] Dealing with potential stock splits in future
- [ ] Decision on dividends

**Comment by zoe-archer** [comment]
Token design here:
https://www.figma.com/file/rbod2zLza3GqwNTYZbO3m1/Synthetix-Brand-Guidelines?node-id=173%3A6385

**Comment by andytcf** [comment]
waiting on chainlink updates
