### ISSUE TITLE
[TASK]: Compare Feature for Kwenta Charts

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#5]
### Summary
Have the ability to view two USD charts layered on top of each other.

### Notes
Visit trading view APIs and 1inch charts for inspiration.

Charting designs: https://www.figma.com/file/sghReDviy1lcr6kkNqlc0e/Kwenta-User-Flows?node-id=0%3A1

### Tasks
- [ ] Implement compare chart

### QA Tasks

- [ ] When selecting two different synths, the chart should show the Synth1/Synth2 overlay (i.e ETH/1inch)

**Comment by andytcf** [comment]
@JChiaramonte7 feel free to delete this one if its a duplicate

**Comment by kelonye** [comment]
The single chart view might need* a new set of chainlink data feeds to support pairs like BTC/XAU? Unless for now we just try approximate the combined rates... @dvd-schwrtz?

**Comment by etn0m** [comment]
duplicate #177
