### ISSUE TITLE
[NEW SYNTH]: sFAANG stocks

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#51]
New Synth Listing Checklist:

- [x] Launch date established (22nd April) 
- [x] Synth icon made (see [Figma doc](https://www.figma.com/file/rbod2zLza3GqwNTYZbO3m1/Synthetix-Brand-Guidelines?node-id=173%3A6385))
- [x] Relevant ecosystem members informed 
- [x] Announcement prepared
- [x] Synthetix.exchange / Kwenta support
- [x] Check if kwenta supports token list/ipfs for assets
- [x] Graph support for Cl Proxy price updates
- [x] Feeds running on CL + aggregator on mainnet
- [x] Market closures for NYSE and bot
- [x] Incentives established
- [x] Create aftermarket trading pool (Balancer pool) 
- [x] Support aftermarket trading pool https://github.com/Synthetixio/kwenta/pull/339
- [x] Dealing with potential stock splits in future
- [x] Decision on dividends

Deployment:

 - Run-through sheet https://docs.google.com/document/d/12InU_joaNlzkV-0ZIS1iq_51EUcR5IJjmERN7BBdzLo/edit

**Comment by andytcf** [comment]
[Chainlink Oracles Available]:

AAPL / USD    8    0x139C8512Cde1778e9b9a8e721ce1aEbd4dD43587
FB / USD    8    0xCe1051646393087e706288C1B57Fd26446657A7f
GOOGL / USD    8    0x36D39936BeA501755921beB5A382a88179070219
NFLX / USD    8    0x67C2e69c5272B94AF3C90683a9947C39Dc605ddE
AMZN / USD    8    0x8994115d287207144236c13Be5E2bDbf6357D9Fd

**Comment by andytcf** [comment]
[Design]: @zoe-archer @erikatruscott-ux do we have the synth icons for these FAANG stocks, it needs to be added into https://github.com/Synthetixio/synthetix-assets

**Comment by andytcf** [comment]
[Dividends and Stock Splits]: Handled by synth circuit breaker

**Comment by zoe-archer** [comment]
<img width="1214" alt="Screen Shot 2021-04-19 at 10 21 58 am" src="https://user-images.githubusercontent.com/46664538/115166979-184e0800-a0f9-11eb-8e18-508d5ef1ff90.png">

Design file here:
https://www.figma.com/file/rbod2zLza3GqwNTYZbO3m1/Synthetix-Brand-Guidelines?node-id=173%3A6385
