### ISSUE TITLE
[NEW SYNTH] sRUNE & s1INCH & sCRV

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#53]
New Synth Listing Checklist:

1INCH + RUNE https://sips.synthetix.io/sips/sip-126

CRV https://sips.synthetix.io/sips/sip-107

- [x] Lanch date established
- [x] Synth icon made 
- [x] Relevant ecosystem members informed 
- [x] Incentives established
- [x] Announcement prepared
- [x] Synthetix.exchange / Kwenta support
- [x] Graph support for Cl Proxy price updates
- [x] Feeds running on CL + aggregator on mainnet
- [x] ~Market closures for NYSE and bot~
- [x] ~Aftermarket trading pool (Balancer pool)~
- [x] ~Dealing with potential stock splits in future~
- [x] ~Decision on dividends~

**Comment by zoe-archer** [comment]
<img width="783" alt="Screen Shot 2021-04-20 at 11 19 51 am" src="https://user-images.githubusercontent.com/46664538/115322911-641cb200-a1ca-11eb-9bb3-e3d10aee3817.png">

Design file here: 
https://www.figma.com/file/rbod2zLza3GqwNTYZbO3m1/Synthetix-Brand-Guidelines?node-id=173%3A6385
