### ISSUE TITLE
A user should be able to see the different governing bodies of Synthetix on the Synthetix Branding page

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#65]
### Summary
- Show the different DAO's (gDAO, ambassadorDAO, Spartan Council, sDAO) with the full DAO name and add copy to explain what they do
- Show the members of each of the DAO's
- Link out to each of the DAO's voting snapshot spaces

**Comment by zoe-archer** [comment]
Possible section structure: 

<img width="1441" alt="Gov-layout" src="https://user-images.githubusercontent.com/46664538/126736011-831b044b-6c12-48a8-b20a-e8a3c29d9fab.png">

**Comment by zoe-archer** [comment]
Garth's initial sketch/mockup of the governing bodies:

<img width="851" alt="IMG_1116_copy 1" src="https://user-images.githubusercontent.com/46664538/126736203-f6017f56-af43-4175-89cd-b920f557244a.png">
