### ISSUE TITLE
[TASK] Futures: Divert the funding to the fee pool

### ISSUE THREAD

**Issue by zyzek** [Synthetixio/issues#87]
Story Points: 3

Funding is simply removed from margin at the moment, and so it simply contributes to the total system debt. However, it should be paid into the fee pool.

- [ ] Set up a per-market "accumulated funding" signed variable.
- [ ] When margin is realised, the funding component needs to be paid into or from this accumulated funding variable (it could go negative).
- [ ] The system debt must account for debt contributed by this accumulated funding
    - [ ] Work out what to do for negative values of the accumulated funding.
- [ ] The funding should be paid into the fee pool periodically (for example when the fee period rolls over), and only transfer if the amount in there is positive.
- [ ] Double check that exchange fees, when paid into the fee pool on order confirmation are properly notifying the fee pool of the transfer.
- [ ] We must ensure that the funding component of a liquidated position is handled properly.
- [ ] Consider, after debt snapshot integration, merging the accumulated funding variables from all markets into a single variable on the manager.
- [ ] Test everything

Note, the accumulated funding variable can be negative if, for example, immediately after a funding sweep, some funding is paid to someone who made funding profit. However, in general there should be more funding paid into the pool than out of the pool, so this should be transient.

**Comment by artdgn** [comment]
outdated
