### ISSUE TITLE
[TASK] Futures: Confirmation/ Liquidation Keeper

### ISSUE THREAD

**Issue by zyzek** [Synthetixio/issues#90]
We need a keeper system that monitors the chain for new orders and confirms them as soon as a new price update comes through. Note that for now we will not be using the chainlink keeper integration until a) it's operating on L2, b) it's out of beta.

## Confirmation Keepers

- [x] Establish how soon after a price update being posted we require orders to be confirmed
- [x] Determine whether keeper needs to operate on a lambda or as a persistent process, given the price update frequency / responsiveness requirements
- [x] If the keeper is a persistent process, we probably also want a monitoring lambda that alerts us if there are are unconfirmed orders lingering for more than one CL price update. The keeper should be able to clear any backlog.
- [x] Must be able to confirm all orders that can be confirmed as soon as a new price comes through from chainlink
- [ ] Should account for cancelled orders
- [ ] Should account for orders cancelled by liquidation
- [ ] Should not confirm orders that cannot be confirmed e.g. because a liquidation is pending

## Liquidations Keepers

We need a keeper system that monitors the chain for positions that can be liquidated, and liquidates them as soon as a price comes through that would liquidate it.

- [x] Establish how soon after a price update being posted we require positions to be liquidated
- [x] Determine whether lambda or persistent process
- [x] Must be able to liquidate all liquidatable positions as soon as they come through from chainlink
- [ ] Should be able to withdraw the liquidation incentives from the account

**Comment by andytcf** [comment]
Testing in progress
